const {chromium}=require(process.env.PLAYWRIGHT_MODULE);
const assert=require('node:assert/strict');
(async()=>{
 const browser=await chromium.launch({channel:'chrome',headless:true});
 const page=await browser.newPage({viewport:{width:1440,height:900}});
 const errors=[]; page.on('pageerror',e=>errors.push(e.message));
 const fixture=await(await page.request.get('http://localhost:3000/api/content')).json();
 let saved;
 await page.route('**/api/admin/content',r=>r.fulfill({json:structuredClone(fixture)}));
 await page.route('**/api/content',r=>{saved=r.request().postDataJSON(); return r.fulfill({json:{updatedAt:new Date().toISOString()}});});
 await page.goto('http://localhost:3000/admin.html');
 assert(!(await page.locator('[data-admin-form]').isVisible()));
 await page.locator('[data-admin-login]').fill('test');
 await page.locator('[data-admin-token]').fill('test');
 await page.locator('[data-login-form] button').click();
 await page.locator('[data-admin-form]').waitFor({state:'visible'});
 assert(!(await page.locator('[data-login-form]').isVisible()));
 await page.locator('[data-admin-nav="news-admin"]').click();
 assert.equal(await page.locator('#news-admin .record-fields[open]').count(),0);
 await page.locator('#news-admin .editor-search').fill(fixture.news[0].title);
 assert.equal(await page.locator('#news-admin [data-editor] > .edit-card:visible').count(),1);
 await page.locator('#news-admin .record-fields:visible > summary').click();
 await page.locator('#news-admin .record-fields:visible textarea').first().fill('Тестовое описание');
 await page.locator('.admin-commandbar button[type=submit]').click();
 await page.waitForTimeout(200);
 assert.equal(saved.news[0].text,'Тестовое описание');
 assert.match(await page.locator('[data-save-state]').innerText(),/сохранены/);
 await page.locator('#news-admin [data-add]').click();
 assert(await page.locator('#news-admin [data-editor] > .edit-card').last().locator('details').first().getAttribute('open')!==null);
 await page.locator('.admin-commandbar button[type=submit]').click();
 await page.screenshot({path:__dirname+'/design-check/admin-simple.png'});
 await page.setViewportSize({width:390,height:900});
 assert(!(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth)));
 await page.screenshot({path:__dirname+'/design-check/admin-simple-mobile.png'});
  assert.deepEqual(errors,[]);
 await page.locator('[data-admin-nav="map"]').click();
 const oldCount = await page.locator('[data-admin-pin]').count();
 await page.locator('[data-admin-map]').click({position:{x:35,y:35}});
 assert.equal(await page.locator('[data-admin-pin]').count(),oldCount+1);
 assert(await page.locator('[data-editor="locations"] > .edit-card').last().locator('.record-fields').getAttribute('open')!==null);
 await page.locator('.admin-commandbar button[type=submit]').click();
 assert.equal(saved.locations.length,fixture.locations.length+1);
 console.log('PASS: login gate, sections, search, expand, edit, add, mocked save, mobile width. No stored content changed.');
 await browser.close();
})();
