const { chromium } = require(process.env.PLAYWRIGHT_MODULE);
const fs = require('fs');
const path = require('path');
const assert = require('node:assert/strict');
(async () => {
  const browser = await chromium.launch({headless:true,channel:'chrome'});
  const page = await browser.newPage();
  // Third-party Twitch internals are outside these local UI regression checks.
  await page.route('https://player.twitch.tv/**', route => route.fulfill({body:'',contentType:'text/html'}));
  const errors = [];
  page.on('pageerror', e => errors.push(e.message));
  fs.mkdirSync(path.join(__dirname,'design-check'),{recursive:true});
  for (const width of [1440,390]) {
    await page.setViewportSize({width,height:900});
    for (const route of ['','wiki.html','map.html','reader.html','ballads.html','legends.html','admin.html']) {
      await page.goto('http://localhost:3000/'+route);
      await page.waitForTimeout(500);
      const overflow = await page.evaluate(() => document.documentElement.scrollWidth > innerWidth);
      console.log(JSON.stringify({width,route:route||'home',overflow}));
      if (!route || route === 'reader.html') {
        const fits = await page.evaluate(() => document.documentElement.scrollHeight <= innerHeight && document.documentElement.scrollWidth <= innerWidth && [...document.querySelectorAll('.home-card')].length === 7 && [...document.querySelectorAll('.home-card')].every(card => card.getBoundingClientRect().bottom <= innerHeight));
        assert(fits, `Home cards must fit the viewport at ${width}px`);
      }
      await page.screenshot({path:path.join(__dirname,'design-check',`${width}-${route||'home'}.png`)});
    }
  }
  await page.goto('http://localhost:3000/');
  await page.locator('#chronicles').click();
  assert(await page.locator('[data-home-panel]').isVisible());
  await page.locator('.home-story-link').first().click();
  assert.equal(await page.locator('[data-home-panel-title]').innerText(),'Соцсети и источники');
  assert(await page.locator('[data-close-home-panel]').evaluate(el=>document.activeElement===el));
  await page.keyboard.press('Escape');
  assert(!(await page.locator('[data-home-panel]').isVisible()));
  assert.equal(await page.locator('.home-stream iframe').count(),0);
  await page.locator('[data-theme-choice="mono"]').click();
  assert.equal(await page.locator('html').getAttribute('data-theme'),'mono');
  await page.goto('http://localhost:3000/wiki.html');
  await page.locator('[data-wiki-tab="locations"]').click();
  assert(await page.locator('[data-wiki-panel="locations"]').isVisible());
  await page.locator('[data-wiki-panel="locations"] .wiki-entry').first().click();
  await page.locator('.wiki-article .avatar-button').click();
  assert(await page.locator('.image-lightbox').isVisible());
  await page.goto('http://localhost:3000/reader.html');
  await page.waitForURL('http://localhost:3000/');
  assert.equal(await page.locator('a[href="/reader.html"]').count(),0);
  await page.goto('http://localhost:3000/map.html');
  await page.locator('.map-pin').last().click();
  assert(await page.locator('.map-pin').last().evaluate(el=>el.classList.contains('active')));
  await page.locator('[data-map-zoom]').fill('180');
  await page.locator('[data-map-zoom]').dispatchEvent('input');
  await page.locator('[data-map-expand]').click();
  await page.waitForTimeout(200);
  assert(await page.evaluate(()=>!!document.fullscreenElement || !!document.querySelector('.map-expanded')));
  await page.locator('[data-map-expand]').click();
  assert(await page.evaluate(()=>!document.fullscreenElement && !document.querySelector('.map-expanded')));
  await page.goto('http://localhost:3000/#map');
  await page.locator('.home-map').click();
  await page.waitForURL('http://localhost:3000/map.html');
  await page.setViewportSize({width:1440,height:900});
  await page.goto('http://localhost:3000/#chronicles');
  await page.locator('.home-story').first().waitFor();
  await page.screenshot({path:path.join(__dirname,'design-check','chronicles.png')});
  await page.setViewportSize({width:390,height:900});
  await page.goto('http://localhost:3000/ballads.html');
  const firstPlaylist = await page.locator('[data-ballad-feature] h1').innerText();
  await page.locator('[data-ballad-next]').click();
  assert.notEqual(await page.locator('[data-ballad-feature] h1').innerText(), firstPlaylist);
  await page.locator('[data-ballad-prev]').click();
  assert.equal(await page.locator('[data-ballad-feature] h1').innerText(), firstPlaylist);
  await page.locator('[data-open-playlist]').click();
  await page.locator('[data-open-track-text]').click();
  await page.locator('[data-close-drawer]').click();
  await page.locator('[data-track-next]').click();
  await page.locator('[data-open-track-text]').click();
  assert.equal(await page.locator('[data-drawer-content] h2').innerText(),await page.locator('[data-dock-title]').innerText());
  await page.locator('[data-close-drawer]').click();
  await page.screenshot({path:path.join(__dirname,'design-check','mobile-player.png')});
  console.log('Collected errors:',errors);
  assert.equal(errors.length,0);
  console.log('Interaction checks passed: home cards and dialogs, theme, wiki, lightbox, reader, map, track lyrics.');
  console.log('JS errors:',errors);
  console.log('Protected endpoint:',(await page.request.get('http://localhost:3000/api/admin/content')).status());
  const fixture = await (await page.request.get('http://localhost:3000/api/content')).json();
  fixture.site.heroImage = '/assets/dark-fantasy-hero.jpg';
  fixture.site.heroTitle = 'Проверка заголовка';
  fixture.site.heroText = 'Проверка описания';
  await page.route('**/api/content', route => route.fulfill({json:fixture}));
  await page.goto('http://localhost:3000/');
  await page.locator('[data-home-heading]').filter({hasText:'Проверка заголовка'}).waitFor();
  assert.equal(await page.locator('[data-site-hero-text]').innerText(),'Проверка описания');
  assert.match(await page.locator('.hero-media').evaluate(el=>getComputedStyle(el).backgroundImage),/dark-fantasy-hero/);
  console.log('Hero content and image override passed without modifying stored data.');
  await browser.close();
})();
